# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  docker: circleci/docker@1.2.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    executor:
      name: docker/docker
      tag: '3.6'
    steps:
      - checkout
      - docker/install-docker-tools
      - run: ./script/build
      - run: ./script/install-deps
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: python -m unittest test.py

workflows:
  # Name the workflow "welcome"
  test:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test