#!/bin/bash
if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

cd ..
# Build docker image
$SUDO docker build . -t "realcore:dev" > /dev/null

$SUDO docker run -t --cap-add SYS_PTRACE -v $(pwd):/src -w /src realcore:dev make all
exit $?