#!/bin/bash
echo Building..
./build
cd ..
for file in $(ls tests | grep .c)
do
  binfile=$(echo "$file" | sed 's/\.c//')
  echo "Testing $file"
  docker run -v $(pwd):/src -w /src realcore:dev gcc /src/tests/$file -o /src/tests/$binfile
  docker run --cap-add SYS_PTRACE -v $(pwd):/src -w /src realcore:dev /src/bin/realcore /src/tests/$binfile
  cat parsley_runner.log
done